const grids50 = [
  {
    name: "Grid 01",
    grid: [
      [null, null, 3, null, 2, null, 6, null, null],
      [9, null, null, 3, null, 5, null, null, 1],
      [null, null, 1, 8, null, 6, 4, null, null],
      [null, null, 8, 1, null, 2, 9, null, null],
      [7, null, null, null, null, null, null, null, 8],
      [null, null, 6, 7, null, 8, 2, null, null],
      [null, null, 2, 6, null, 9, 5, null, null],
      [8, null, null, 2, null, 3, null, null, 9],
      [null, null, 5, null, 1, null, 3, null, null],
    ],
  },
  {
    name: "Grid 02",
    grid: [
      [2, null, null, null, 8, null, 3, null, null],
      [null, 6, null, null, 7, null, null, 8, 4],
      [null, 3, null, 5, null, null, 2, null, 9],
      [null, null, null, 1, null, 5, 4, null, 8],
      [null, null, null, null, null, null, null, null, null],
      [4, null, 2, 7, null, 6, null, null, null],
      [3, null, 1, null, null, 7, null, 4, null],
      [7, 2, null, null, 4, null, null, 6, null],
      [null, null, 4, null, 1, null, null, null, 3],
    ],
  },
  {
    name: "Grid 03",
    grid: [
      [null, null, null, null, null, null, 9, null, 7],
      [null, null, null, 4, 2, null, 1, 8, null],
      [null, null, null, 7, null, 5, null, 2, 6],
      [1, null, null, 9, null, 4, null, null, null],
      [null, 5, null, null, null, null, null, 4, null],
      [null, null, null, 5, null, 7, null, null, 9],
      [9, 2, null, 1, null, 8, null, null, null],
      [null, 3, 4, null, 5, 9, null, null, null],
      [5, null, 7, null, null, null, null, null, null],
    ],
  },
  {
    name: "Grid 04",
    grid: [
      [null, 3, null, null, 5, null, null, 4, null],
      [null, null, 8, null, 1, null, 5, null, null],
      [4, 6, null, null, null, null, null, 1, 2],
      [null, 7, null, 5, null, 2, null, 8, null],
      [null, null, null, 6, null, 3, null, null, null],
      [null, 4, null, 1, null, 9, null, 3, null],
      [2, 5, null, null, null, null, null, 9, 8],
      [null, null, 1, null, 2, null, 6, null, null],
      [null, 8, null, null, 6, null, null, 2, null],
    ],
  },
  {
    name: "Grid 05",
    grid: [
      [null, 2, null, 8, 1, null, 7, 4, null],
      [7, null, null, null, null, 3, 1, null, null],
      [null, 9, null, null, null, 2, 8, null, 5],
      [null, null, 9, null, 4, null, null, 8, 7],
      [4, null, null, 2, null, 8, null, null, 3],
      [1, 6, null, null, 3, null, 2, null, null],
      [3, null, 2, 7, null, null, null, 6, null],
      [null, null, 5, 6, null, null, null, null, 8],
      [null, 7, 6, null, 5, 1, null, 9, null],
    ],
  },
  {
    name: "Grid 06",
    grid: [
      [1, null, null, 9, 2, null, null, null, null],
      [5, 2, 4, null, 1, null, null, null, null],
      [null, null, null, null, null, null, null, 7, null],
      [null, 5, null, null, null, 8, 1, null, 2],
      [null, null, null, null, null, null, null, null, null],
      [4, null, 2, 7, null, null, null, 9, null],
      [null, 6, null, null, null, null, null, null, null],
      [null, null, null, null, 3, null, 9, 4, 5],
      [null, null, null, null, 7, 1, null, null, 6],
    ],
  },
  {
    name: "Grid 07",
    grid: [
      [null, 4, 3, null, 8, null, 2, 5, null],
      [6, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, 1, null, 9, 4],
      [9, null, null, null, null, 4, null, 7, null],
      [null, null, null, 6, null, 8, null, null, null],
      [null, 1, null, 2, null, null, null, null, 3],
      [8, 2, null, 5, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, 5],
      [null, 3, 4, null, 9, null, 7, 1, null],
    ],
  },
  {
    name: "Grid 08",
    grid: [
      [4, 8, null, null, null, 6, 9, null, 2],
      [null, null, 2, null, null, 8, null, null, 1],
      [9, null, null, 3, 7, null, null, 6, null],
      [8, 4, null, null, 1, null, 2, null, null],
      [null, null, 3, 7, null, 4, 1, null, null],
      [null, null, 1, null, 6, null, null, 4, 9],
      [null, 2, null, null, 8, 5, null, null, 7],
      [7, null, null, 9, null, null, 6, null, null],
      [6, null, 9, 2, null, null, null, 1, 8],
    ],
  },
  {
    name: "Grid 09",
    grid: [
      [null, null, null, 9, null, null, null, null, 2],
      [null, 5, null, 1, 2, 3, 4, null, null],
      [null, 3, null, null, null, null, 1, 6, null],
      [9, null, 8, null, null, null, null, null, null],
      [null, 7, null, null, null, null, null, 9, null],
      [null, null, null, null, null, null, 2, null, 5],
      [null, 9, 1, null, null, null, null, 5, null],
      [null, null, 7, 4, 3, 9, null, 2, null],
      [4, null, null, null, null, 7, null, null, null],
    ],
  },
  {
    name: "Grid 10",
    grid: [
      [null, null, 1, 9, null, null, null, null, 3],
      [9, null, null, 7, null, null, 1, 6, null],
      [null, 3, null, null, null, 5, null, null, 7],
      [null, 5, null, null, null, null, null, null, 9],
      [null, null, 4, 3, null, 2, 6, null, null],
      [2, null, null, null, null, null, null, 7, null],
      [6, null, null, 1, null, null, null, 3, null],
      [null, 4, 2, null, null, 7, null, null, 6],
      [5, null, null, null, null, 6, 8, null, null],
    ],
  },
  {
    name: "Grid 11",
    grid: [
      [null, null, null, 1, 2, 5, 4, null, null],
      [null, null, 8, 4, null, null, null, null, null],
      [4, 2, null, 8, null, null, null, null, null],
      [null, 3, null, null, null, null, null, 9, 5],
      [null, 6, null, 9, null, 2, null, 1, null],
      [5, 1, null, null, null, null, null, 6, null],
      [null, null, null, null, null, 3, null, 4, 9],
      [null, null, null, null, null, 7, 2, null, null],
      [null, null, 1, 2, 9, 8, null, null, null],
    ],
  },
  {
    name: "Grid 12",
    grid: [
      [null, 6, 2, 3, 4, null, 7, 5, null],
      [1, null, null, null, null, 5, 6, null, null],
      [5, 7, null, null, null, null, null, 4, null],
      [null, null, null, null, 9, 4, 8, null, null],
      [4, null, null, null, null, null, null, null, 6],
      [null, null, 5, 8, 3, null, null, null, null],
      [null, 3, null, null, null, null, null, 9, 1],
      [null, null, 6, 4, null, null, null, null, 7],
      [null, 5, 9, null, 8, 3, 2, 6, null],
    ],
  },
  {
    name: "Grid 13",
    grid: [
      [3, null, null, null, null, null, null, null, null],
      [null, null, 5, null, null, 9, null, null, null],
      [2, null, null, 5, null, 4, null, null, null],
      [null, 2, null, null, null, null, 7, null, null],
      [1, 6, null, null, null, null, null, 5, 8],
      [7, null, 4, 3, 1, null, 6, null, null],
      [null, null, null, 8, 9, null, 1, null, null],
      [null, null, null, null, 6, 7, null, 8, null],
      [null, null, null, null, null, 5, 4, 3, 7],
    ],
  },
  {
    name: "Grid 14",
    grid: [
      [6, 3, null, null, null, null, null, null, null],
      [null, null, null, 5, null, null, null, null, 8],
      [null, null, 5, 6, 7, 4, null, null, null],
      [null, null, null, null, 2, null, null, null, null],
      [null, null, 3, 4, null, 1, null, 2, null],
      [null, null, null, null, null, null, 3, 4, 5],
      [null, null, null, null, null, 7, null, null, 4],
      [null, 8, null, 3, null, null, 9, null, 2],
      [9, 4, 7, 1, null, null, null, 8, null],
    ],
  },
  {
    name: "Grid 15",
    grid: [
      [null, null, null, null, 2, null, null, 4, null],
      [null, null, 8, null, 3, 5, null, null, null],
      [null, null, null, null, 7, null, 6, null, 2],
      [null, 3, 1, null, 4, 6, 9, 7, null],
      [2, null, null, null, null, null, null, null, null],
      [null, null, null, 5, null, 1, 2, null, 3],
      [null, 4, 9, null, null, null, 7, 3, null],
      [null, null, null, null, null, null, null, 1, null],
      [8, null, null, null, null, 4, null, null, null],
    ],
  },
  {
    name: "Grid 16",
    grid: [
      [3, 6, 1, null, 2, 5, 9, null, null],
      [null, 8, null, 9, 6, null, null, 1, null],
      [4, null, null, null, null, null, null, 5, 7],
      [null, null, 8, null, null, null, 4, 7, 1],
      [null, null, null, 6, null, 3, null, null, null],
      [2, 5, 9, null, null, null, 8, null, null],
      [7, 4, null, null, null, null, null, null, 5],
      [null, 2, null, null, 1, 8, null, 6, null],
      [null, null, 5, 4, 7, null, 3, 2, 9],
    ],
  },
  {
    name: "Grid 17",
    grid: [
      [null, 5, null, 8, null, 7, null, 2, null],
      [6, null, null, null, 1, null, null, 9, null],
      [7, null, 2, 5, 4, null, null, null, 6],
      [null, 7, null, null, 2, null, 3, null, 1],
      [5, null, 4, null, null, null, 9, null, 8],
      [1, null, 3, null, 8, null, null, 7, null],
      [9, null, null, null, 7, 6, 2, null, 5],
      [null, 6, null, null, 9, null, null, null, 3],
      [null, 8, null, 1, null, 3, null, 4, null],
    ],
  },
  {
    name: "Grid 18",
    grid: [
      [null, 8, null, null, null, 5, null, null, null],
      [null, null, null, null, null, 3, 4, 5, 7],
      [null, null, null, null, 7, null, 8, null, 9],
      [null, 6, null, 4, null, null, 9, null, 3],
      [null, null, 7, null, 1, null, 5, null, null],
      [4, null, 8, null, null, 7, null, 2, null],
      [9, null, 1, null, 2, null, null, null, null],
      [8, 4, 2, 3, null, null, null, null, null],
      [null, null, null, 1, null, null, null, 8, null],
    ],
  },
  {
    name: "Grid 19",
    grid: [
      [null, null, 3, 5, null, 2, 9, null, null],
      [null, null, null, null, 4, null, null, null, null],
      [1, null, 6, null, null, null, 3, null, 5],
      [9, null, null, 2, 5, 1, null, null, 8],
      [null, 7, null, 4, null, 8, null, 3, null],
      [8, null, null, 7, 6, 3, null, null, 1],
      [3, null, 8, null, null, null, 1, null, 4],
      [null, null, null, null, 2, null, null, null, null],
      [null, null, 5, 1, null, 4, 8, null, null],
    ],
  },
  {
    name: "Grid 20",
    grid: [
      [null, null, null, null, null, null, null, null, null],
      [null, null, 9, 8, null, 5, 1, null, null],
      [null, 5, 1, 9, null, 7, 4, 2, null],
      [2, 9, null, 4, null, 1, null, 6, 5],
      [null, null, null, null, null, null, null, null, null],
      [1, 4, null, 5, null, 8, null, 9, 3],
      [null, 2, 6, 7, null, 9, 5, 8, null],
      [null, null, 5, 1, null, 3, 6, null, null],
      [null, null, null, null, null, null, null, null, null],
    ],
  },
  {
    name: "Grid 21",
    grid: [
      [null, 2, null, null, 3, null, null, 9, null],
      [null, null, null, 9, null, 7, null, null, null],
      [9, null, null, 2, null, 8, null, null, 5],
      [null, null, 4, 8, null, 6, 5, null, null],
      [6, null, 7, null, null, null, 2, null, 8],
      [null, null, 3, 1, null, 2, 9, null, null],
      [8, null, null, 6, null, 5, null, null, 7],
      [null, null, null, 3, null, 9, null, null, null],
      [null, 3, null, null, 2, null, null, 5, null],
    ],
  },
  {
    name: "Grid 22",
    grid: [
      [null, null, 5, null, null, null, null, null, 6],
      [null, 7, null, null, null, 9, null, 2, null],
      [null, null, null, 5, null, null, 1, null, 7],
      [8, null, 4, 1, 5, null, null, null, null],
      [null, null, null, 8, null, 3, null, null, null],
      [null, null, null, null, 9, 2, 8, null, 5],
      [9, null, 7, null, null, 6, null, null, null],
      [null, 3, null, 4, null, null, null, 1, null],
      [2, null, null, null, null, null, 6, null, null],
    ],
  },
  {
    name: "Grid 23",
    grid: [
      [null, 4, null, null, null, null, null, 5, null],
      [null, null, 1, 9, 4, 3, 6, null, null],
      [null, null, 9, null, null, null, 3, null, null],
      [6, null, null, null, 5, null, null, null, 2],
      [1, null, 3, null, null, null, 5, null, 6],
      [8, null, null, null, 2, null, null, null, 7],
      [null, null, 5, null, null, null, 2, null, null],
      [null, null, 2, 4, 3, 6, 7, null, null],
      [null, 3, null, null, null, null, null, 4, null],
    ],
  },
  {
    name: "Grid 24",
    grid: [
      [null, null, 4, null, null, null, null, null, null],
      [null, null, null, null, 3, null, null, null, 2],
      [3, 9, null, 7, null, null, null, 8, null],
      [4, null, null, null, null, 9, null, null, 1],
      [2, null, 9, 8, null, 1, 3, null, 7],
      [6, null, null, 2, null, null, null, null, 8],
      [null, 1, null, null, null, 8, null, 5, 3],
      [9, null, null, null, 4, null, null, null, null],
      [null, null, null, null, null, null, 8, null, null],
    ],
  },
  {
    name: "Grid 25",
    grid: [
      [3, 6, null, null, 2, null, null, 8, 9],
      [null, null, null, 3, 6, 1, null, null, null],
      [null, null, null, null, null, null, null, null, null],
      [8, null, 3, null, null, null, 6, null, 2],
      [4, null, null, 6, null, 3, null, null, 7],
      [6, null, 7, null, null, null, 1, null, 8],
      [null, null, null, null, null, null, null, null, null],
      [null, null, null, 4, 1, 8, null, null, null],
      [9, 7, null, null, 3, null, null, 1, 4],
    ],
  },
  {
    name: "Grid 26",
    grid: [
      [5, null, null, 4, null, null, null, 6, null],
      [null, null, 9, null, null, null, 8, null, null],
      [6, 4, null, null, 2, null, null, null, null],
      [null, null, null, null, null, 1, null, null, 8],
      [2, null, 8, null, null, null, 5, null, 1],
      [7, null, null, 5, null, null, null, null, null],
      [null, null, null, null, 9, null, null, 8, 4],
      [null, null, 3, null, null, null, 6, null, null],
      [null, 6, null, null, null, 3, null, null, 2],
    ],
  },
  {
    name: "Grid 27",
    grid: [
      [null, null, 7, 2, 5, 6, 4, null, null],
      [4, null, null, null, null, null, null, null, 5],
      [null, 1, null, null, 3, null, null, 6, null],
      [null, null, null, 5, null, 8, null, null, null],
      [null, null, 8, null, 6, null, 2, null, null],
      [null, null, null, 1, null, 7, null, null, null],
      [null, 3, null, null, 7, null, null, 9, null],
      [2, null, null, null, null, null, null, null, 4],
      [null, null, 6, 3, 1, 2, 7, null, null],
    ],
  },
  {
    name: "Grid 28",
    grid: [
      [null, null, null, null, null, null, null, null, null],
      [null, 7, 9, null, 5, null, 1, 8, null],
      [8, null, null, null, null, null, null, null, 7],
      [null, null, 7, 3, null, 6, 8, null, null],
      [4, 5, null, 7, null, 8, null, 9, 6],
      [null, null, 3, 5, null, 2, 7, null, null],
      [7, null, null, null, null, null, null, null, 5],
      [null, 1, 6, null, 3, null, 4, 2, null],
      [null, null, null, null, null, null, null, null, null],
    ],
  },
  {
    name: "Grid 29",
    grid: [
      [null, 3, null, null, null, null, null, 8, null],
      [null, null, 9, null, null, null, 5, null, null],
      [null, null, 7, 5, null, 9, 2, null, null],
      [7, null, null, 1, null, 5, null, null, 8],
      [null, 2, null, null, 9, null, null, 3, null],
      [9, null, null, 4, null, 2, null, null, 1],
      [null, null, 4, 2, null, 7, 1, null, null],
      [null, null, 2, null, null, null, 8, null, null],
      [null, 7, null, null, null, null, null, 9, null],
    ],
  },
  {
    name: "Grid 30",
    grid: [
      [2, null, null, 1, 7, null, 6, null, 3],
      [null, 5, null, null, null, null, 1, null, null],
      [null, null, null, null, null, 6, null, 7, 9],
      [null, null, null, null, 4, null, 7, null, null],
      [null, null, null, 8, null, 1, null, null, null],
      [null, null, 9, null, 5, null, null, null, null],
      [3, 1, null, 4, null, null, null, null, null],
      [null, null, 5, null, null, null, null, 6, null],
      [9, null, 6, null, 3, 7, null, null, 2],
    ],
  },
  {
    name: "Grid 31",
    grid: [
      [null, null, null, null, null, null, null, 8, null],
      [8, null, null, 7, null, 1, null, 4, null],
      [null, 4, null, null, 2, null, null, 3, null],
      [3, 7, 4, null, null, null, 9, null, null],
      [null, null, null, null, 3, null, null, null, null],
      [null, null, 5, null, null, null, 3, 2, 1],
      [null, 1, null, null, 6, null, null, 5, null],
      [null, 5, null, 8, null, 2, null, null, 6],
      [null, 8, null, null, null, null, null, null, null],
    ],
  },
  {
    name: "Grid 32",
    grid: [
      [null, null, null, null, null, null, null, 8, 5],
      [null, null, null, 2, 1, null, null, null, 9],
      [9, 6, null, null, 8, null, 1, null, null],
      [5, null, null, 8, null, null, null, 1, 6],
      [null, null, null, null, null, null, null, null, null],
      [8, 9, null, null, null, 6, null, null, 7],
      [null, null, 9, null, 7, null, null, 5, 2],
      [3, null, null, null, 5, 4, null, null, null],
      [4, 8, null, null, null, null, null, null, null],
    ],
  },
  {
    name: "Grid 33",
    grid: [
      [6, null, 8, null, 7, null, 5, null, 2],
      [null, 5, null, 6, null, 8, null, 7, null],
      [null, null, 2, null, null, null, 3, null, null],
      [5, null, null, null, 9, null, null, null, 6],
      [null, 4, null, 3, null, 2, null, 5, null],
      [8, null, null, null, 5, null, null, null, 3],
      [null, null, 5, null, null, null, 2, null, null],
      [null, 1, null, 7, null, 4, null, 9, null],
      [4, null, 9, null, 6, null, 7, null, 1],
    ],
  },
  {
    name: "Grid 34",
    grid: [
      [null, 5, null, null, 1, null, null, 4, null],
      [1, null, 7, null, null, null, 6, null, 2],
      [null, null, null, 9, null, 5, null, null, null],
      [2, null, 8, null, 3, null, 5, null, 1],
      [null, 4, null, null, 7, null, null, 2, null],
      [9, null, 1, null, 8, null, 4, null, 6],
      [null, null, null, 4, null, 1, null, null, null],
      [3, null, 4, null, null, null, 7, null, 9],
      [null, 2, null, null, 6, null, null, 1, null],
    ],
  },
  {
    name: "Grid 35",
    grid: [
      [null, 5, 3, null, null, null, 7, 9, null],
      [null, null, 9, 7, 5, 3, 4, null, null],
      [1, null, null, null, null, null, null, null, 2],
      [null, 9, null, null, 8, null, null, 1, null],
      [null, null, null, 9, null, 7, null, null, null],
      [null, 8, null, null, 3, null, null, 7, null],
      [5, null, null, null, null, null, null, null, 3],
      [null, null, 7, 6, 4, 1, 2, null, null],
      [null, 6, 1, null, null, null, 9, 4, null],
    ],
  },
  {
    name: "Grid 36",
    grid: [
      [null, null, 6, null, 8, null, 3, null, null],
      [null, 4, 9, null, 7, null, 2, 5, null],
      [null, null, null, 4, null, 5, null, null, null],
      [6, null, null, 3, 1, 7, null, null, 4],
      [null, null, 7, null, null, null, 8, null, null],
      [1, null, null, 8, 2, 6, null, null, 9],
      [null, null, null, 7, null, 2, null, null, null],
      [null, 7, 5, null, 4, null, 1, 9, null],
      [null, null, 3, null, 9, null, 6, null, null],
    ],
  },
  {
    name: "Grid 37",
    grid: [
      [null, null, 5, null, 8, null, 7, null, null],
      [7, null, null, 2, null, 4, null, null, 5],
      [3, 2, null, null, null, null, null, 8, 4],
      [null, 6, null, 1, null, 5, null, 4, null],
      [null, null, 8, null, null, null, 5, null, null],
      [null, 7, null, 8, null, 3, null, 1, null],
      [4, 5, null, null, null, null, null, 9, 1],
      [6, null, null, 5, null, 8, null, null, 7],
      [null, null, 3, null, 1, null, 6, null, null],
    ],
  },
  {
    name: "Grid 38",
    grid: [
      [null, null, null, 9, null, null, 8, null, null],
      [1, 2, 8, null, null, 6, 4, null, null],
      [null, 7, null, 8, null, null, null, 6, null],
      [8, null, null, 4, 3, null, null, null, 7],
      [5, null, null, null, null, null, null, null, 9],
      [6, null, null, null, 7, 9, null, null, 8],
      [null, 9, null, null, null, 4, null, 1, null],
      [null, null, 3, 6, null, null, 2, 8, 4],
      [null, null, 1, null, null, 7, null, null, null],
    ],
  },
  {
    name: "Grid 39",
    grid: [
      [null, null, null, null, 8, null, null, null, null],
      [2, 7, null, null, null, null, null, 5, 4],
      [null, 9, 5, null, null, null, 8, 1, null],
      [null, null, 9, 8, null, 6, 4, null, null],
      [null, 2, null, 4, null, 3, null, 6, null],
      [null, null, 6, 9, null, 5, 1, null, null],
      [null, 1, 7, null, null, null, 6, 2, null],
      [4, 6, null, null, null, null, null, 3, 8],
      [null, null, null, null, 9, null, null, null, null],
    ],
  },
  {
    name: "Grid 40",
    grid: [
      [null, null, null, 6, null, 2, null, null, null],
      [4, null, null, null, 5, null, null, null, 1],
      [null, 8, 5, null, 1, null, 6, 2, null],
      [null, 3, 8, 2, null, 6, 7, 1, null],
      [null, null, null, null, null, null, null, null, null],
      [null, 1, 9, 4, null, 7, 3, 5, null],
      [null, 2, 6, null, 4, null, 5, 3, null],
      [9, null, null, null, 2, null, null, null, 7],
      [null, null, null, 8, null, 9, null, null, null],
    ],
  },
  {
    name: "Grid 41",
    grid: [
      [null, null, null, 9, null, null, null, null, 2],
      [null, 5, null, 1, 2, 3, 4, null, null],
      [null, 3, null, null, null, null, 1, 6, null],
      [9, null, 8, null, null, null, null, null, null],
      [null, 7, null, null, null, null, null, 9, null],
      [null, null, null, null, null, null, 2, null, 5],
      [null, 9, 1, null, null, null, null, 5, null],
      [null, null, 7, 4, 3, 9, null, 2, null],
      [4, null, null, null, null, 7, null, null, null],
    ],
  },
  {
    name: "Grid 42",
    grid: [
      [3, 8, null, null, null, null, null, null, null],
      [null, null, null, 4, null, null, 7, 8, 5],
      [null, null, 9, null, 2, null, 3, null, null],
      [null, 6, null, null, 9, null, null, null, null],
      [8, null, null, 3, null, 2, null, null, 9],
      [null, null, null, null, 4, null, null, 7, null],
      [null, null, 1, null, 7, null, 5, null, null],
      [4, 9, 5, null, null, 6, null, null, null],
      [null, null, null, null, null, null, null, 9, 2],
    ],
  },
  {
    name: "Grid 43",
    grid: [
      [null, null, null, 1, 5, 8, null, null, null],
      [null, null, 2, null, 6, null, 8, null, null],
      [null, 3, null, null, null, null, null, 4, null],
      [null, 2, 7, null, 3, null, 5, 1, null],
      [null, null, null, null, null, null, null, null, null],
      [null, 4, 6, null, 8, null, 7, 9, null],
      [null, 5, null, null, null, null, null, 8, null],
      [null, null, 4, null, 7, null, 1, null, null],
      [null, null, null, 3, 2, 5, null, null, null],
    ],
  },
  {
    name: "Grid 44",
    grid: [
      [null, 1, null, 5, null, null, 2, null, null],
      [9, null, null, null, null, 1, null, null, null],
      [null, null, 2, null, null, 8, null, 3, null],
      [5, null, null, null, 3, null, null, null, 7],
      [null, null, 8, null, null, null, 5, null, null],
      [6, null, null, null, 8, null, null, null, 4],
      [null, 4, null, 1, null, null, 7, null, null],
      [null, null, null, 7, null, null, null, null, 6],
      [null, null, 3, null, null, 4, null, 5, null],
    ],
  },
  {
    name: "Grid 45",
    grid: [
      [null, 8, null, null, null, null, null, 4, null],
      [null, null, null, 4, 6, 9, null, null, null],
      [4, null, null, null, null, null, null, null, 7],
      [null, null, 5, 9, null, 4, 6, null, null],
      [null, 7, null, 6, null, 8, null, 3, null],
      [null, null, 8, 5, null, 2, 1, null, null],
      [9, null, null, null, null, null, null, null, 5],
      [null, null, null, 7, 8, 1, null, null, null],
      [null, 6, null, null, null, null, null, 1, null],
    ],
  },
  {
    name: "Grid 46",
    grid: [
      [9, null, 4, 2, null, null, null, null, 7],
      [null, 1, null, null, null, null, null, null, null],
      [null, null, null, 7, null, 6, 5, null, null],
      [null, null, null, 8, null, null, null, 9, null],
      [null, 2, null, 9, null, 4, null, 6, null],
      [null, 4, null, null, null, 2, null, null, null],
      [null, null, 1, 6, null, 7, null, null, null],
      [null, null, null, null, null, null, null, 3, null],
      [3, null, null, null, null, 5, 7, null, 2],
    ],
  },
  {
    name: "Grid 47",
    grid: [
      [null, null, null, 7, null, null, 8, null, null],
      [null, null, 6, null, null, null, null, 3, 1],
      [null, 4, null, null, null, 2, null, null, null],
      [null, 2, 4, null, 7, null, null, null, null],
      [null, 1, null, null, 3, null, null, 8, null],
      [null, null, null, null, 6, null, 2, 9, null],
      [null, null, null, 8, null, null, null, 7, null],
      [8, 6, null, null, null, null, 5, null, null],
      [null, null, 2, null, null, 6, null, null, null],
    ],
  },
  {
    name: "Grid 48",
    grid: [
      [null, null, 1, null, null, 7, null, 9, null],
      [5, 9, null, null, 8, null, null, null, 1],
      [null, 3, null, null, null, null, null, 8, null],
      [null, null, null, null, null, 5, 8, null, null],
      [null, 5, null, null, 6, null, null, 2, null],
      [null, null, 4, 1, null, null, null, null, null],
      [null, 8, null, null, null, null, null, 3, null],
      [1, null, null, null, 2, null, null, 7, 9],
      [null, 2, null, 7, null, null, 4, null, null],
    ],
  },
  {
    name: "Grid 49",
    grid: [
      [null, null, null, null, null, 3, null, 1, 7],
      [null, 1, 5, null, null, 9, null, null, 8],
      [null, 6, null, null, null, null, null, null, null],
      [1, null, null, null, null, 7, null, null, null],
      [null, null, 9, null, null, null, 2, null, null],
      [null, null, null, 5, null, null, null, null, 4],
      [null, null, null, null, null, null, null, 2, null],
      [5, null, null, 6, null, null, 3, 4, null],
      [3, 4, null, 2, null, null, null, null, null],
    ],
  },
  {
    name: "Grid 50",
    grid: [
      [3, null, null, 2, null, null, null, null, null],
      [null, null, null, 1, null, 7, null, null, null],
      [7, null, 6, null, 3, null, 5, null, null],
      [null, 7, null, null, null, 9, null, 8, null],
      [9, null, null, null, 2, null, null, null, 4],
      [null, 1, null, 8, null, null, null, 5, null],
      [null, null, 9, null, 4, null, 3, null, 1],
      [null, null, null, 7, null, 2, null, null, null],
      [null, null, null, null, null, 8, null, null, 6],
    ],
  },
];
module.exports = { grids50 };
